### ISSUE TITLE
Application crashes when --commitEmail flag is not supplied

### ISSUE THREAD

**Issue by HarelM** [coveralls-net/coveralls.net#27]
When all flag are in their correct place and all the data is present except --commitEmail, the application crashes (ran it from powershell) using latest stable Nuget package:

```
PS> Invoke-Expression $cmd
output file 'cov.json' already exists and will be overwritten.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at csmacnz.Coveralls.MainArgs.get_OptCommitemail() in c:\projects\coveralls-net\src\csmacnz.Coveralls\T4DocoptNet.cs:
line 84
   at csmacnz.Coveralls.CommandLineGitDataResolver.GenerateData() in c:\projects\coveralls-net\src\csmacnz.Coveralls\Com
mandLineGitDataResolver.cs:line 26
   at csmacnz.Coveralls.Program.<ResolveGitData>b__d(IGitDataResolver p) in c:\projects\coveralls-net\src\csmacnz.Covera
lls\Program.cs:line 182
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at csmacnz.Coveralls.Program.ResolveGitData(MainArgs args) in c:\projects\coveralls-net\src\csmacnz.Coveralls\Program
.cs:line 182
   at csmacnz.Coveralls.Program.Main(String[] argv) in c:\projects\coveralls-net\src\csmacnz.Coveralls\Program.cs:line 1
18
```

**Comment by jdeering** [comment]
Based on the namespace in the exception, the code you are running is for another project - https://github.com/csMACnz/coveralls.net

This project's NuGet package can be found here - https://www.nuget.org/packages/coveralls.io/

**Comment by HarelM** [comment]
Sorry, my mistake... both projects have almost the same name...
