### ISSUE TITLE
Executing command-line throws NRE

### ISSUE THREAD

**Issue by matkoch** [coveralls-net/coveralls.net#34]
I'm getting a NRE when executing in a random folder.

> An unknown exception has occurred.
Object reference not set to an instance of an object.
   at Coveralls.CoverallsBootstrap.get_CoverageFiles() in c:\projects\coveralls-net-gmbph\Coveralls.Lib\CoverallsBootstrap.cs:line 102
   at Coveralls.Net.Program.Run(CommandLineOptions options) in c:\projects\coveralls-net-gmbph\coveralls.net\Program.cs:line 40
   at Coveralls.Net.Program.Main(String[] args) in c:\projects\coveralls-net-gmbph\coveralls.net\Program.cs:line 18

**Comment by jdeering** [comment]
Can you provide the exact command you ran that caused this error? I've narrowed down possible causes, but I'll need the exact command syntax in order to verify it.

**Comment by matkoch** [comment]
No parameters, just invoking the executable.
