### ISSUE TITLE
Can't find a part of  the path

### ISSUE THREAD

**Issue by jakeonrails** [coveralls-net/coveralls.net#45]
Command line: `.\packages\coveralls.io.1.4.2\tools\coveralls.net.exe --opencover .\ReportApiTest.Results.xml -r %COVERALLS_REPO_TOKEN%`

Results:

```
An unknown exception has occurred.
Could not find a part of the path 'C:\projects\moq4\src\Moq\obj\TypeNameFormatter.cs'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.File.OpenRead(String path)
   at Coveralls.Net.LocalFileSystem.ComputeHash(String path) in C:\Users\jason\src\open-source\coveralls.net\coveralls.net\LocalFileSystem.cs:line 28
   at Coveralls.CoverallsBootstrap.get_CoverageFiles() in C:\Users\jason\src\open-source\coveralls.net\Coveralls.Lib\CoverallsBootstrap.cs:line 124
   at Coveralls.Net.Program.Run(CommandLineOptions options) in C:\Users\jason\src\open-source\coveralls.net\coveralls.net\Program.cs:line 40
   at Coveralls.Net.Program.Main(String[] args) in C:\Users\jason\src\open-source\coveralls.net\coveralls.net\Program.cs:line 18
```

**Comment by jakeonrails** [comment]
Just installed  1.3.4 b/c github says that's the latest version and I get the same error
